.TH TINES 1 "26 Dec 2015"
.SH NAME
Tines \- outliner, planner, organizer, notebook
.SH SYNOPSIS
.B tines
.RI [ file ]
.RI [ options ]
.RI [ command
.RI [ command ]
\&\.\.\.]
.SH DESCRIPTION
Tines is an ncurses-based outliner
with planning and organizing capabilities.
You can use it in two different ways:
.IP \[bu] 4
As an outliner, reading and writing
to the file specified on the command line.
Tines supports OPML, its own XML-based format,
or indented ASCII.
.IP \[bu]
As an organizer, storing outlines, calendars,
action lists, project lists, tracking lists,
notes, and most other kinds of text data, in a single file.
.LP
Tines can import and export OPML and indented text files,
and additionally can export to HTML and PostScript.
.LP
Running Tines without specifying a file
loads the default ~/.hnb file.
If the file does not exist, Tines creates the file
and populates it with example data.
.SH OPTIONS
Tines can be invoked with the following options:
.TP 4
.B \-h, \-\-help
Shows a summary of options.
.TP
.B \-v, \-\-version
Shows the version of Tines on your system.
.TP
.B \-t, \-\-tutorial
Loads an example database instead of a file.
.TP
.BR \-rc \ <\fIfile\fP>
Loads the specified config file (the default is ~/.hnbrc).
.TP
.BR \-ui \ < curses | cli >
Specifies the user interface to use.
The default is
.BR curses .
The
.B cli
option is useful for scripting Tines,
or debugging and testing.
.TP
.B \-e
Runs CLI commands in noninteractive mode.
In this mode, Tines starts in CLI mode.
Type `help' to get more information.
.SH FILES
.TP
~/.hnb
The default file for your notes.
To use a different file, specify its name on the command line.
.TP
~/.hnbrc
The default configuration file. To load an other config file than default,
use the
.B -rc
command-line option.
.SH SEE ALSO
For more information on the usage of the program,
load the tutorial or
press
.B F1
while running Tines.
.LP
Tines is a fork of the
.I hnb
outliner,
written by \[/O]yvind Kol\[:a]s (pippin@users.sourceforge.net).
For information about Tines, see
https://github.com/larrykollar/tines/wiki
.LP
To get the latest version of Tines, see
https://github.com/larrykollar/tines/
.SH AUTHOR
The original
.I hnb
was written by
\[/O]yvind Kol\[:a]s (pippin@users.sourceforge.net).
.LP
Tines is now maintained by Larry Kollar.
.LP
This manual page was originally written by Andras Bali <drewie@bigfoot.com>,
and has been heavily modified for Tines by Larry Kollar.
