/*
 * file_opml.c -- generic xml import/export filters for Tines
 *
 * Copyright (C) 2001-2003 Øyvind Kolås <pippin@users.sourceforge.net>
 * Modified for Tines by Larry Kollar, 2016
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free
 * Software Foundation; either version 2, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc., 59
 * Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 */

#if HAVE_CONFIG_H
#include <config.h>
#endif

#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "xml_tok.h"

#include "cli.h"
#include "tree.h"

#include "file.h"
#include "prefs.h"
#include "query.h"
#include "util_string.h"

#define indent(count,char)	{int j;for(j=0;j<count;j++)fprintf(file,char);}

/* *INDENT-OFF* */

static char *xmlquote[]={
	"<","&lt;",
	">","&gt;",
	"&","&amp;",
	"\"","&quot;",
	"'","&apos;",
	NULL
};

static char *xmlunquote[]={
	"&lt;","<",
	"&gt;",">",
	"&amp;","&",
	"&quot;","\"",
	"&apos;","'",
	NULL
};

/* *INDENT-ON* */

/* OPML variables */
static char opml_title[128]   = "Outline exported from Tines"; /* title */
static char opml_created[36]  = ""; /* dateCreated */
static char opml_mod[36]      = ""; /* dateModified */
static char opml_owner[128]   = ""; /* ownerName */
static char opml_email[256]   = ""; /* ownerEmail */
static char opml_exp[1024]    = ""; /* expansionState */
static char opml_scroll[128]  = ""; /* vertScrollState */
static int  opml_top          = 20; /* windowTop */
static int  opml_left         = 20; /* windowLeft */
static int  opml_bot          = 660; /* windowBottom */
static int  opml_right        = 660; /* windowRight */

static void opml_export_nodes (FILE * file, Node *node, int level, int saveall)
{
	int done = -1; /* -1 = no done attribute; 0 = "no"; 1 = "yes" */
	int todo = 0;  /*  1 if type="todo" */
	int text = 0;  /*  1 if type="text" */

	while (node) {
		done = -1;
		todo = 0;
		text = 0;

		fprintf (file, "\n");
		indent (level, "\t");
		fprintf (file, "<outline");

		{Node_AttItem *att=node->attrib;
			/* build our output map on first pass */
/*			while(att) {
				if(!strcmp(att->name, "done") {
					if(!strcmp(att->data, "yes")) {
						done = 1;
					} else {
						done = 0;
					}
				}
				if(!strcmp(att->name, "type")) {
					if(!strcmp(att->data, "text")) text = 1;
					if(!strcmp(att->data, "todo")) todo = 1;
				}
			}
		 */
		 while(att){
		 	char *quoted=string_replace(att->data,xmlquote);
			fprintf (file, " %s=\"%s\"", att->name, quoted);
			free(quoted);
			att=att->next;
		 }
		}

		if (node_right (node)) {
			fprintf (file, ">");

			opml_export_nodes (file, node_right (node), level+1, 0);
			fprintf (file, "\n");
			indent (level, "\t");
			fprintf (file, "</outline>");
		} else {
			fprintf (file, " />");
		}

		/* needs to only export one branch at level 0 */
		if( level || saveall )
			node = node_down (node);
		else
			break;
	}
}

static void* export_opml (int argc, char **argv, void *data)
{
	Node *node = (Node *) data;
	char *filename;
	int saveall;
	FILE *file;

	/* argv[0]: name used to invoke this command
	 * argv[1]: file name
	 * argv[2]: node position */

	filename = fn_expand( argc>=2?argv[1]:"", 1	);

	if (!strcmp (filename, "-") || !strcmp(filename, ""))
		file = stdout;
	else
		file = fopen (filename, "w");

	if (!file) {
		cli_outfunf ("opml export, unable to open \"%s\"", filename);
		return node;
	}

	fprintf (file, "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n\
<?pos=\"%s\"?>\n\
<!-- generated by tines %s (https://github.com/larrykollar/tines) -->\n\
<opml version=\"1.0\">\n", argc==3?argv[2]:"1", VERSION);
	fprintf (file,
	"<head>\n\
		<title>%s</title>\n\
		<dateCreated>%s</dateCreated>\n\
		<dateModified>%s</dateModified>\n\
		<ownerName>%s</ownerName>\n\
		<ownerEmail>%s</ownerEmail>\n\
		<expansionState>%s</expansionState>\n\
		<vertScrollState>%s</vertScrollState>\n\
		<windowTop>%d</windowTop>\n\
		<windowLeft>%d</windowLeft>\n\
		<windowBottom>%d</windowBottom>\n\
		<windowRight>%d</windowRight>\n\
		</head>\n\
	<body>\n",
			opml_title, opml_created, opml_mod, opml_owner, opml_email,
			opml_exp, opml_scroll, opml_top, opml_left, opml_bot, opml_right);

	/* saveall = 0 if we're only saving the branch */
	saveall = strcmp(argv[0], "export_opml_branch");

	opml_export_nodes (file, node, 0, saveall);

	fprintf (file, "\n</body>\n</opml>\n");
	if (file != stdout)
		fclose (file);

	cli_outfunf ("opml export, wrote data to \"%s\"", filename);

	return node;
}

static void* import_opml (int argc, char **argv, void *data)
{
	Node *node = (Node *) data;
	char *filename;
	char *rdata;
	int type;
	int in_body = 0;
	int in_head = 0;
	int in_outlineelement = 0;
	int level = -1;
	xml_tok_state *s;
	import_state_t ist;

	Node *tempnode=NULL;
	FILE *file;

	filename = fn_expand( argc==2?argv[1]:"", 0	);

	file = fopen (filename, "r");
	if (!file) {
		cli_outfunf ("opml import, unable to open \"%s\"", filename);
		return node;
	}
	s = xml_tok_init (file);
	init_import (&ist, node);

	while (((type = xml_tok_get (s, &rdata)) != t_eof) && (type != t_error)) {
		if (type == t_error) { /* does this code ever get run? */
			cli_outfunf ("opml import error, parsing '%s', line:%i %s", filename,
						 s->line_no, rdata);
			fclose (file);
			return node;
		}
		if (in_body) {
			if (type == t_tag && !strcmp (rdata, "outline")) {
				level++;
				in_outlineelement = 1;
				tempnode=node_new();
				continue;
			}
			if (in_outlineelement && type == t_att){
				char *att_name=strdup(rdata);
				char *unquoted;
				if(xml_tok_get(s,&rdata)!=t_val){
					cli_outfun("import_opml: OPML violation: attribute has no value");
				};
				unquoted=string_replace(rdata,xmlunquote);

				node_set(tempnode,att_name,unquoted);
				free(unquoted);
				free(att_name);
				continue;
			}
			if ((type == t_endtag || type == t_closeemptytag)
				&& !strcmp (rdata, "outline")) {
				in_outlineelement = 0;
				import_node(&ist, level, tempnode);	/* will free tempnode */
				tempnode=NULL;
			}
			if ((type == t_closetag || type == t_closeemptytag)
				&& !strcmp (rdata, "outline")) {
				level--;
				continue;
			}
				/* process head elements */
/*		} else {
			if( in_head ) {
				if (type == t_tag && !strcmp (rdata, "title")) {
					level++;
					in_outlineelement = 1;
					tempnode=node_new();
					continue;
				}
			}
		} else {
			if (type == t_tag && !strcmp (rdata, "head")) {
				in_body = 0;
				in_head = 1;
			} */
		} else {
			if (type == t_tag && !strcmp (rdata, "body")) {
				in_body = 1;
				in_head = 0;
			}
		}
	}

	if (node_getflag (node, F_temp))
		node = node_remove (node);	/* remove temporary node, if tree was empty */

	cli_outfunf ("opml import - imported \"%s\" %i lines", filename, s->line_no);
	xml_tok_cleanup (s);
	return node;
}


/*
!init_file_opml();
*/
void init_file_opml ()
{
	cli_add_command ("export_opml", export_opml, "<filename>");
	cli_add_command ("export_opml_branch", export_opml, "<filename>");
	cli_add_help ("export_opml",
		"Exports the current entry, following siblings, and child entries in OPML format.");
	cli_add_help ("export_opml_branch",
		"Exports the current entry and child entries in OPML format.");
	cli_add_command ("import_opml", import_opml, "<filename>");
	cli_add_help ("import_opml",
		"Imports the specified OPML file below the current entry.");
}
